In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

df1=pd.read_excel('副本监测数据.xlsx',sheet_name=0)
df2=pd.read_excel('副本监测数据.xlsx',sheet_name=1)
df3=pd.read_excel('副本监测数据.xlsx',sheet_name=2)
df4=pd.read_excel('副本监测数据.xlsx',sheet_name=3)
df1 =df1.to_numpy()
df2 =df2.to_numpy()
df3 =df3.to_numpy()
df4 =df4.to_numpy()
df = [df1,df2,df3,df4]
df

[array([[-19.03, -18.91, -19.36, -18.56, -19.51, -17.99],
        [-18.91, -19.3 , -19.12, -18.98, -19.43, -19.9 ],
        [-18.92, -19.24, -19.08, -18.65, -19.3 , -18.69],
        [-18.62, -18.84, -18.48, -18.45, -18.9 , -18.41],
        [-18.84, -18.54, -18.72, -19.  , -18.69, -19.31],
        [-18.91, -18.69, -18.79, -19.49, -18.75, -19.01],
        [-19.08, -18.54, -18.72, -18.34, -18.64, -17.69],
        [-19.25, -19.54, -19.51, -19.49, -19.  , -19.74],
        [-19.5 , -19.87, -19.25, -20.27, -19.2 , -20.31],
        [-19.67, -19.99, -19.95, -19.28, -19.89, -20.39],
        [-19.89, -20.01, -19.94, -20.16, -20.05, -21.44],
        [-19.51, -20.5 , -19.9 , -20.35, -19.99, -19.64],
        [-19.84, -19.85, -19.56, -19.6 , -20.12, -19.42],
        [-19.73, -19.95, -19.8 , -20.05, -19.89, -18.43],
        [-20.13, -19.87, -19.96, -20.58, -20.2 , -19.96],
        [-19.7 , -19.78, -19.59, -19.8 , -19.95, -20.06],
        [-19.98, -19.81, -20.13, -19.02, -20.16, -20.16],
        [-19.1

In [2]:

smelist1=[]
srmelist1=[]
maelist1=[]
mapelist1=[]
smapelist1=[]
r_squaredlist1=[]
for dataframe in df:
    smelist=[]
    srmelist=[]
    maelist=[]
    mapelist=[]
    smapelist=[]
    r_squaredlist=[]
    for k in range(1,dataframe.shape[1]):
        sme = mean_squared_error(dataframe[:, 0], dataframe[:, k])
        srme = np.sqrt(sme)
        mae = mean_absolute_error(dataframe[:, 0], dataframe[:, k])
        mape = np.mean(np.abs((dataframe[:, 0] - dataframe[:, k]) / dataframe[:, 0]))
        smape = np.mean(np.abs(dataframe[:, 0] - dataframe[:, k]) / np.abs((dataframe[:, 0] + dataframe[:, k]) / 2))
        r_squared = r2_score(dataframe[:, 0], dataframe[:, k])

        smelist.append(sme)
        srmelist.append(srme)
        maelist.append(mae)
        mapelist.append(mape)
        smapelist.append(smape)
        r_squaredlist.append(r_squared)

    smelist1.append(smelist)
    srmelist1.append(srmelist)
    maelist1.append(maelist)
    mapelist1.append(mapelist)
    smapelist1.append(smapelist)
    r_squaredlist1.append(r_squaredlist)

# 将列表转换为NumPy数组
smelist1 = np.array(smelist1)
srmelist1 = np.array(srmelist1)
maelist1 = np.array(maelist1)
mapelist1 = np.array(mapelist1)
smapelist1 = np.array(smapelist1)
r_squaredlist1 = np.array(r_squaredlist1)

# 打印结果
print("SME List:\n", smelist1)
print("SRMSE List:\n", srmelist1)
print("MAE List:\n", maelist1)
print("MAPE List:\n", mapelist1)
print("SMAPE List:\n", smapelist1)
print("R-squared List:\n", r_squaredlist1)

SME List:
 [[1.27156667e-01 4.63100000e-02 3.78313333e-01 1.07800000e-01
  7.15316667e-01]
 [1.10513333e-01 4.22800000e-02 3.05146667e-01 1.01476667e-01
  8.24860000e-01]
 [1.19470000e-01 5.05833233e+01 3.60230000e-01 1.18623333e-01
  6.55586667e-01]
 [1.07456667e-01 5.63766667e-02 2.46990000e-01 1.21066667e-01
  8.99070000e-01]]
SRMSE List:
 [[0.35659033 0.21519758 0.61507181 0.3283291  0.84576395]
 [0.33243546 0.20562101 0.55240082 0.31855402 0.90821804]
 [0.34564433 7.11219539 0.60019164 0.34441738 0.80968307]
 [0.32780584 0.23743771 0.49698088 0.34794636 0.94819302]]
MAE List:
 [[0.289      0.189      0.528      0.29066667 0.721     ]
 [0.28933333 0.178      0.50866667 0.27566667 0.77866667]
 [0.295      1.465      0.53766667 0.285      0.68333333]
 [0.27966667 0.19833333 0.40766667 0.284      0.84033333]]
MAPE List:
 [[0.01433832 0.00950479 0.02605614 0.01462005 0.03625946]
 [0.01452461 0.00903209 0.02579572 0.01395499 0.0398555 ]
 [0.01478833 0.07517896 0.02720619 0.01444827 0.03

C:\Users\64473\AppData\Local\Temp\ipykernel_23168\114632315.py:19: RuntimeWarning: divide by zero encountered in divide
  smape = np.mean(np.abs(dataframe[:, 0] - dataframe[:, k]) / np.abs((dataframe[:, 0] + dataframe[:, k]) / 2))


In [4]:
results_df = pd.DataFrame({
    'SME': smelist1.flatten(),
    'SRMSE': srmelist1.flatten(),
    'MAE': maelist1.flatten(),
    'MAPE': mapelist1.flatten(),
    'SMAPE': smapelist1.flatten(),
    'R-squared': r_squaredlist1.flatten()
})

# 保存到CSV文件
results_df.to_csv("results.csv", index=False)